# Conda recipe for Magni

package:
  name: magni
  version: '1.4.0'

source:
  fn: magni-1.4.0.tar.gz
  url: https://pypi.python.org/packages/source/m/magni/magni-1.4.0.tar.gz
  md5: 36b5edfef43846fd8956f4e1ced85b3a

  patches:
    - setup_py_conda.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pytables
    - scipy
    - matplotlib

test:
  requires:
    - nose

  imports:
    - magni

about:
  home: https://github.com/SIP-AAU/Magni
  license: BSD 2-Clause
  summary: A Python Package for Compressive Sampling Reconstruction of Atomic Force Microscopy Images
  
